-- جدول إعدادات النظام
CREATE TABLE IF NOT EXISTS system_settings (
    id SERIAL PRIMARY KEY,
    organization_id INTEGER,
    company_name VARCHAR(255),
    company_name_en VARCHAR(255),
    company_email VARCHAR(255),
    company_phone VARCHAR(50),
    company_address TEXT,
    company_website VARCHAR(255),
    tax_number VARCHAR(100),
    commercial_register VARCHAR(100),
    default_currency VARCHAR(10) DEFAULT 'SAR',
    language VARCHAR(10) DEFAULT 'ar',
    timezone VARCHAR(50) DEFAULT 'Asia/Riyadh',
    date_format VARCHAR(20) DEFAULT 'DD/MM/YYYY',
    time_format VARCHAR(20) DEFAULT '24h',
    fiscal_year_start DATE,
    auto_numbering BOOLEAN DEFAULT true,
    numbering_system VARCHAR(20) DEFAULT 'sequential',
    invoice_prefix VARCHAR(10) DEFAULT 'INV',
    invoice_start INTEGER DEFAULT 1,
    order_prefix VARCHAR(10) DEFAULT 'SO',
    order_start INTEGER DEFAULT 1,
    purchase_prefix VARCHAR(10) DEFAULT 'PO',
    purchase_start INTEGER DEFAULT 1,
    customer_prefix VARCHAR(10) DEFAULT 'CUS',
    customer_start INTEGER DEFAULT 1,
    supplier_prefix VARCHAR(10) DEFAULT 'SUP',
    supplier_start INTEGER DEFAULT 1,
    item_prefix VARCHAR(10) DEFAULT 'ITM',
    item_start INTEGER DEFAULT 1,
    item_group_prefix VARCHAR(10) DEFAULT 'GRP',
    item_group_start INTEGER DEFAULT 1,
    paper_size VARCHAR(20) DEFAULT 'A4',
    print_logo BOOLEAN DEFAULT true,
    print_footer BOOLEAN DEFAULT true,
    default_printer VARCHAR(255),
    working_days JSONB DEFAULT '["Sunday","Monday","Tuesday","Wednesday","Thursday"]'::jsonb,
    working_hours VARCHAR(50) DEFAULT '08:00-17:00',
    session_timeout INTEGER DEFAULT 30,
    two_factor_auth BOOLEAN DEFAULT false,
    password_policy VARCHAR(50) DEFAULT 'medium',
    audit_log BOOLEAN DEFAULT true,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
