-- جدول المنتجات
CREATE TABLE IF NOT EXISTS products (
    id SERIAL PRIMARY KEY,
    product_code VARCHAR(100) UNIQUE NOT NULL,
    product_name VARCHAR(255) NOT NULL,
    product_name_en VARCHAR(255),
    barcode VARCHAR(100),
    description TEXT,
    category VARCHAR(100),
    subcategory VARCHAR(100),
    classifications VARCHAR(255),
    product_type VARCHAR(50),
    brand VARCHAR(100),
    model VARCHAR(100),
    manufacturer_number VARCHAR(100),
    original_number VARCHAR(100),
    supplier_id INTEGER REFERENCES suppliers(id),
    supplier_name VARCHAR(255),
    supplier_code VARCHAR(100),
    main_unit VARCHAR(50),
    secondary_unit VARCHAR(50),
    conversion_factor NUMERIC(10,4) DEFAULT 1,
    selling_price NUMERIC(15,2),
    retail_price NUMERIC(15,2),
    wholesale_price NUMERIC(15,2),
    last_purchase_price NUMERIC(15,2),
    average_cost NUMERIC(15,2),
    currency VARCHAR(10) DEFAULT 'SAR',
    tax_rate NUMERIC(5,2) DEFAULT 0,
    discount_rate NUMERIC(5,2) DEFAULT 0,
    min_stock_level NUMERIC(15,2),
    max_stock_level NUMERIC(15,2),
    reorder_point NUMERIC(15,2),
    order_quantity NUMERIC(15,2),
    max_quantity NUMERIC(15,2),
    location VARCHAR(100),
    weight NUMERIC(10,2),
    dimensions VARCHAR(100),
    color VARCHAR(50),
    size VARCHAR(50),
    material VARCHAR(100),
    country_of_origin VARCHAR(100),
    warranty_period INTEGER,
    shelf_life INTEGER,
    has_batch BOOLEAN DEFAULT false,
    batch_tracking BOOLEAN DEFAULT false,
    has_expiry BOOLEAN DEFAULT false,
    expiry_tracking BOOLEAN DEFAULT false,
    serial_tracking BOOLEAN DEFAULT false,
    has_colors BOOLEAN DEFAULT false,
    status VARCHAR(20) DEFAULT 'active',
    entry_date DATE,
    image_url TEXT,
    product_image TEXT,
    attachments TEXT,
    notes TEXT,
    general_notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_products_code ON products(product_code);
CREATE INDEX IF NOT EXISTS idx_products_name ON products(product_name);
CREATE INDEX IF NOT EXISTS idx_products_barcode ON products(barcode);
CREATE INDEX IF NOT EXISTS idx_products_category ON products(category);
CREATE INDEX IF NOT EXISTS idx_products_supplier ON products(supplier_id);
CREATE INDEX IF NOT EXISTS idx_products_status ON products(status);
