-- جدول إعدادات الطباعة
CREATE TABLE IF NOT EXISTS print_settings (
    id SERIAL PRIMARY KEY,
    company_id INTEGER,
    invoice_template VARCHAR(50) DEFAULT 'modern',
    paper_size VARCHAR(20) DEFAULT 'A4',
    orientation VARCHAR(20) DEFAULT 'portrait',
    margin_top NUMERIC(5,2) DEFAULT 1.0,
    margin_bottom NUMERIC(5,2) DEFAULT 1.0,
    margin_left NUMERIC(5,2) DEFAULT 1.0,
    margin_right NUMERIC(5,2) DEFAULT 1.0,
    show_logo BOOLEAN DEFAULT true,
    logo_size VARCHAR(20) DEFAULT 'medium',
    logo_position VARCHAR(20) DEFAULT 'left',
    show_header BOOLEAN DEFAULT true,
    header_text TEXT,
    show_footer BOOLEAN DEFAULT true,
    footer_text TEXT,
    show_company_info BOOLEAN DEFAULT true,
    show_bank_details BOOLEAN DEFAULT false,
    show_payment_terms BOOLEAN DEFAULT true,
    show_page_numbers BOOLEAN DEFAULT true,
    show_print_date BOOLEAN DEFAULT true,
    font_family VARCHAR(100) DEFAULT 'Cairo',
    font_size INTEGER DEFAULT 12,
    primary_color VARCHAR(20) DEFAULT '#3b82f6',
    secondary_color VARCHAR(20) DEFAULT '#64748b',
    use_colors BOOLEAN DEFAULT true,
    auto_print BOOLEAN DEFAULT false,
    print_copies INTEGER DEFAULT 1,
    default_printer VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
